#!/usr/bin/python
import re
import sys

def get_series():
    searched = {'DISTRIB_ID': None , 'DISTRIB_CODENAME': None}
    with open('/etc/lsb-release', 'r') as fh:
        for line in fh:
            key, value = line.strip().split("=")
            if key in searched.keys():
                searched[key] = value.lower()
    series = "%s-%s" % (searched['DISTRIB_ID'], searched['DISTRIB_CODENAME'])
    return series

def verify_series(seeked):
    running = get_series()
    if seeked.strip() == running:
        return True
    return False

for line in sys.stdin:
    matched = False

    start_tokens = "^\[(.+?)\]\s+"
    m = re.search(start_tokens, line)
    if m is not None:
        matched = True
        rest = line[m.end():]

    end_tokens = "\s+(\[(.*)\])$"
    m = re.search(end_tokens, line.strip())
    if m is not None:
        matched = True
        rest = line[:m.start()]

    if not matched:
        print line,
        continue

    if any(map(verify_series, m.group(2).split(" "))):
        print rest
