#!/bin/sh
# OpenContrail developers <dev@lists.opencontrail.org>

set -e

if [ "${1}" = "purge" ] ; then

  if (which deluser && getent passwd contrail) > /dev/null 2>&1; then
    deluser --system --quiet contrail || true
  fi

  if (which delgroup && getent group contrail) > /dev/null 2>&1; then
    delgroup --system --quiet contrail || true
  fi

  rm -rf /var/log/contrail-webui /var/lib/contrail-webui

fi

#DEBHELPER#
