.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "IFMAP\-SERVER" "1" "May 2014" "" ""
.
.SH "NAME"
\fBifmap\-server\fR \- OpenContrail IFMAP
.
.SH "SYNOPSIS"
\fBifmap\-server\fR
.
.SH "DESCRIPTION"
OpenContrail ifmap\-server is a wrapper on irond server\.
.
.P
irond is an experimental IF\-MAP 2\.0 compliant MAP server written in JAVA\. irond supports both basic authentication and certificate\-based authentication (using X\.509 certificates) of MAP clients\.
.
.P
irond is maintained by the Trust@HsH group at the Hochschule Hannover, initial development was carried out during the ESUKOM research project\.
.
.SH "BUGS"
Contrail is hosted in Launchpad so you can view current bugs at https://bugs\.launchpad\.net/opencontrail/\.
.
.SH "AUTHOR"
OpenContrail developers \fIdev@lists\.opencontrail\.org\fR
.
.SH "COPYRIGHT"
Copyright (c) 2014 OpenContrail
