#! /bin/sh
cat <<EOF
Package                                Version                 Build-ID | Repo | RPM Name
-------------------------------------- ----------------------- ----------------------------------
contrail-analytics                     1-1304082216        148
openstack-dashboard.noarch             2012.1.3-1.fc17     updates
contrail-agent                         1-1304091654        contrail-agent-1-1304091654.x86_64
EOF
