#!/bin/sh
# OpenContrail developers <dev@lists.opencontrail.org>

set -e

if [ "${1}" = "purge" ] ; then

  # Del user contrail (and backup home)
  if (which deluser && getent passwd contrail) > /dev/null 2>&1; then
    deluser --system --quiet --backup-to /var/lib contrail || true
  fi

  # Del group contrail
  if (which delgroup && getent group contrail) > /dev/null 2>&1; then
    delgroup --system --quiet contrail || true
  fi

  rm -f /var/log/contrail/api-*-zk.log*
  rm -f /var/log/contrail/contrail-api.log*
  rm -f /var/log/contrail/contrail-api-*-stdout.log*
  rm -f /var/log/contrail/contrail-device-manager.log*
  rm -f /var/log/contrail/contrail-device-manager-stdout.log*
  rm -f /var/log/contrail/device-manager-zk.log*
  rm -f /var/log/contrail/contrail-schema.log*
  rm -f /var/log/contrail/contrail-schema-stdout.log*
  rm -f /var/log/contrail/schema-zk.log*
  rm -f /var/log/contrail/contrail-svc-monitor.log*
  rm -f /var/log/contrail/contrail-svc-monitor-stdout.log*
  rm -f /var/log/contrail/svc-monitor.err*
  rm -f /var/log/contrail/svc-monitor-zk.log*
  rm -f /var/log/contrail/discovery.log*
  rm -f /var/log/contrail/contrail-discovery-*-stdout.log*
  rm -f /var/log/contrail/contrail-config-nodemgr-stdout.log*
  rm -f /var/log/contrail/contrail-config-nodemgr-stderr.log*
  rm -f /var/log/contrail/process_statecontrail-config.json

  if [ ! "$(ls -A /var/log/contrail)" ]; then
    rm -rf /var/log/contrail
  fi

  if [ ! "$(ls -A /var/lib/contrail)" ]; then
    rm -rf /var/lib/contrail
  fi

fi

#DEBHELPER#
