#!/bin/sh

set -e

case "$1" in
    (configure)
        :
    ;;
    (abort-upgrade|abort-remove|abort-deconfigure)
      exit 0
    ;;
    (*)
      echo "postinst called with unknown argument \`$1'" >&2
      exit 0
    ;;
esac

# Replace documentation directory with symlink
docdir="/usr/share/doc/contrail-vrouter-dbg"
if [ -d $docdir -a ! -L $docdir ]; then
    if rmdir $docdir 2>/dev/null; then
        ln -sf contrail-vrouter $docdir
    fi
fi

#DEBHELPER#

exit 0
