#!/bin/sh
# OpenContrail developers <dev@lists.opencontrail.org>

set -e

if [ "${1}" = "purge" ] ; then

  # Del user contrail (and backup home)
  if (which deluser && getent passwd contrail) > /dev/null 2>&1; then
    deluser --system --quiet --backup-to /var/lib contrail || true
  fi

  # Del group contrail
  if (which delgroup && getent group contrail) > /dev/null 2>&1; then
    delgroup --system --quiet contrail || true
  fi

  rm -f /var/log/contrail/contrail-analytics-api.log*
  rm -f /var/log/contrail/contrail-analytics-api-stdout.log*
  rm -f /var/log/contrail/contrail-analytics-nodemgr-stderr.log*
  rm -f /var/log/contrail/contrail-analytics-nodemgr-stdout.log*
  rm -f /var/log/contrail/contrail-collector.log*
  rm -f /var/log/contrail/contrail-collector-stdout.log*
  rm -f /var/log/contrail/contrail-query-engine.log*
  rm -f /var/log/contrail/contrail-query-engine-stdout.log*
  rm -f /var/log/contrail/contrail-alarm-gen.log*
  rm -f /var/log/contrail/contrail-alarm-gen-stdout.log*
  rm -f /var/log/contrail/contrail-snmp-collector.log*
  rm -f /var/log/contrail/contrail-snmp-collector-stdout.log*
  rm -f /var/log/contrail/contrail-topology.log*
  rm -f /var/log/contrail/contrail-topology-stdout.log*
  rm -f /var/log/contrail/process_statecontrail-analytics.json
  rm -f /var/log/contrail/supervisord-analytics.log*

  if [ ! "$(ls -A /var/log/contrail)" ]; then
    rm -rf /var/log/contrail
  fi

  if [ ! "$(ls -A /var/lib/contrail)" ]; then
    rm -rf /var/lib/contrail
  fi
fi

#DEBHELPER#
