#!/bin/sh
# OpenContrail developers <dev@lists.opencontrail.org>

set -e

if [ "${1}" = "purge" ] ; then

  # Del user contrail (and backup home)
  if (which deluser && getent passwd contrail) > /dev/null 2>&1; then
    deluser --system --quiet --backup-to /var/lib contrail || true
  fi

  # Del group contrail
  if (which delgroup && getent group contrail) > /dev/null 2>&1; then
    delgroup --system --quiet contrail || true
  fi

  # Remove log files
  rm -f /var/log/contrail/contrail-vrouter-agent.log*
  rm -f /var/log/contrail/contrail-vrouter-agent-stdout.log*
  rm -f /var/log/contrail/contrail-tor-agent*
  rm -f /var/log/contrail/contrail-vrouter-nodemgr-stderr.log*
  rm -f /var/log/contrail/contrail-vrouter-nodemgr-stdout.log*
  rm -f /var/log/contrail/process_statecontrail-vrouter.json
  if (ls /var/log/contrail/supervisord-vrouter.log* 1> /dev/null 2>&1); then
      rm -f /var/log/contrail/supervisord-vrouter.log*
  fi


  if [ ! "$(ls -A /var/log/contrail)" ]; then
    rm -rf /var/log/contrail
  fi

  rm -rf /var/lib/contrail/ports /var/lib/contrail/dhcp /var/lib/contrail/backup
  if [ ! "$(ls -A /var/lib/contrail)" ]; then
    rm -rf /var/lib/contrail
  fi
fi

#DEBHELPER#
