#!/bin/sh
# OpenContrail developers <dev@lists.opencontrail.org>

set -e

if [ "${1}" = "purge" ] ; then

  # Del user contrail (and backup home)
  if (which deluser && getent passwd contrail) > /dev/null 2>&1; then
    deluser --system --quiet --backup-to /var/lib contrail || true
  fi

  # Del group contrail
  if (which delgroup && getent group contrail) > /dev/null 2>&1; then
    delgroup --system --quiet contrail || true
  fi

  rm -rf /var/log/named /var/lib/contrail

fi

#DEBHELPER#
